language: ruby
script: true
jobs:
  include:
    - language: python
      env: EXTRA_TESTS=true
      if: type = api
      script: true
    - language: ruby
      env: NO_EXTRA_TESTS=true
      script: true
